services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-fipe
    restart: always
    environment:
      POSTGRES_DB: fipe_db
      POSTGRES_USER: fipe
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fipe-network

  api-fipe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-fipe
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - fipe-network
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://fipe:senha123@postgres:5432/fipe_db
      - NO_PROXY=localhost,127.0.0.1,0.0.0.0,postgres
      - no_proxy=localhost,127.0.0.1,0.0.0.0,postgres

volumes:
  postgres_data:

networks:
  fipe-network:
    driver: bridge
